POST http://localhost:5000/api/students
Content-Type: application/json

[
  {
    "stu_id": "550101",
    "stu_name": "Arjun Reddy",
    "gender": "Male",
    "parent_name": "Suresh Reddy",
    "parents_phone_number": "8519813814",
    "class_section": "10-A",
    "bus_no": "55",
    "is_bus_student": true,
    "address": "Krishna Lanka",
    "transport_fee": 12000
  },
  {
    "stu_id": "550102",
    "stu_name": "Vinay Kumar",
    "gender": "Male",
    "parent_name": "Ravi Kumar",
    "parents_phone_number": "8885310346",
    "class_section": "9-B",
    "bus_no": "55",
    "is_bus_student": true,
    "address": "Bapanayyanagar",
    "transport_fee": 14500
  },
  {
    "stu_id": "550103",
    "stu_name": "Rajesh Babu",
    "gender": "Male",
    "parent_name": "Madhav Babu",
    "parents_phone_number": "9542370332",
    "class_section": "8-C",
    "bus_no": "55",
    "is_bus_student": true,
    "address": "Benz Circle",
    "transport_fee": 13000
  },
  {
    "stu_id": "550104",
    "stu_name": "Suresh Naik",
    "gender": "Male",
    "parent_name": "Prakash Naik",
    "parents_phone_number": "9000000004",
    "class_section": "7-A",
    "bus_no": "55",
    "is_bus_student": true,
    "address": "Patamata",
    "transport_fee": 15500
  },
  {
    "stu_id": "550105",
    "stu_name": "Naveen Das",
    "gender": "Male",
    "parent_name": "Ramesh Das",
    "parents_phone_number": "9000000005",
    "class_section": "10-B",
    "bus_no": "55",
    "is_bus_student": true,
    "address": "Autonagar",
    "transport_fee": 17000
  },
  {
    "stu_id": "550106",
    "stu_name": "Kiran Rao",
    "gender": "Male",
    "parent_name": "Venkatesh Rao",
    "parents_phone_number": "9000000006",
    "class_section": "9-A",
    "bus_no": "55",
    "is_bus_student": true,
    "address": "Krishna Lanka",
    "transport_fee": 18000
  },
  {
    "stu_id": "550107",
    "stu_name": "Deepak S",
    "gender": "Male",
    "parent_name": "Harish S",
    "parents_phone_number": "9000000007",
    "class_section": "7-B",
    "bus_no": "55",
    "is_bus_student": true,
    "address": "Bapanayyanagar",
    "transport_fee": 11000
  },
  {
    "stu_id": "550108",
    "stu_name": "Raj Kumar",
    "gender": "Male",
    "parent_name": "Satish Kumar",
    "parents_phone_number": "9000000008",
    "class_section": "8-A",
    "bus_no": "55",
    "is_bus_student": true,
    "address": "Benz Circle",
    "transport_fee": 15000
  },
  {
    "stu_id": "550109",
    "stu_name": "Kishore M",
    "gender": "Male",
    "parent_name": "Raju M",
    "parents_phone_number": "9000000009",
    "class_section": "9-C",
    "bus_no": "55",
    "is_bus_student": true,
    "address": "Patamata",
    "transport_fee": 14000
  },
  {
    "stu_id": "550110",
    "stu_name": "Anand R",
    "gender": "Male",
    "parent_name": "Chandra Reddy",
    "parents_phone_number": "9000000010",
    "class_section": "10-C",
    "bus_no": "55",
    "is_bus_student": true,
    "address": "Autonagar",
    "transport_fee": 13500
  },
  {
    "stu_id": "550111",
    "stu_name": "Anjali K",
    "gender": "Female",
    "parent_name": "Lakshmi K",
    "parents_phone_number": "9000000011",
    "class_section": "8-B",
    "bus_no": "-",
    "is_bus_student": false,
    "address": "American Hospital",
    "transport_fee": 0
  },
  {
    "stu_id": "550112",
    "stu_name": "Meena S",
    "gender": "Female",
    "parent_name": "Radha S",
    "parents_phone_number": "9000000012",
    "class_section": "7-C",
    "bus_no": "-",
    "is_bus_student": false,
    "address": "Patamata",
    "transport_fee": 0
  },
  {
    "stu_id": "550113",
    "stu_name": "Divya P",
    "gender": "Female",
    "parent_name": "Saraswati P",
    "parents_phone_number": "9000000013",
    "class_section": "10-A",
    "bus_no": "-",
    "is_bus_student": false,
    "address": "Benz Circle",
    "transport_fee": 0
  },
  {
    "stu_id": "550114",
    "stu_name": "Neha T",
    "gender": "Female",
    "parent_name": "Sunitha T",
    "parents_phone_number": "9000000014",
    "class_section": "9-B",
    "bus_no": "-",
    "is_bus_student": false,
    "address": "Bapanayyanagar",
    "transport_fee": 0
  },
  {
    "stu_id": "550115",
    "stu_name": "Swathi M",
    "gender": "Female",
    "parent_name": "Anjali M",
    "parents_phone_number": "9000000015",
    "class_section": "8-C",
    "bus_no": "-",
    "is_bus_student": false,
    "address": "Krishna Lanka",
    "transport_fee": 0
  },
  {
    "stu_id": "550116",
    "stu_name": "Shruti R",
    "gender": "Female",
    "parent_name": "Kavitha R",
    "parents_phone_number": "9000000016",
    "class_section": "7-A",
    "bus_no": "77",
    "is_bus_student": true,
    "address": "Eluru Road",
    "transport_fee": 11500
  },
  {
    "stu_id": "550117",
    "stu_name": "Kavya V",
    "gender": "Female",
    "parent_name": "Padma V",
    "parents_phone_number": "9000000017",
    "class_section": "9-C",
    "bus_no": "77",
    "is_bus_student": true,
    "address": "Benz Circle",
    "transport_fee": 12500
  },
  {
    "stu_id": "550118",
    "stu_name": "Sandhya N",
    "gender": "Female",
    "parent_name": "Nirmala N",
    "parents_phone_number": "9000000018",
    "class_section": "10-B",
    "bus_no": "77",
    "is_bus_student": true,
    "address": "Autonagar",
    "transport_fee": 17500
  },
  {
    "stu_id": "550119",
    "stu_name": "Bhavana L",
    "gender": "Female",
    "parent_name": "Neelima L",
    "parents_phone_number": "9000000019",
    "class_section": "9-A",
    "bus_no": "66",
    "is_bus_student": true,
    "address": "Bhavanipuram",
    "transport_fee": 16000
  },
  {
    "stu_id": "550120",
    "stu_name": "Prajakta D",
    "gender": "Female",
    "parent_name": "Sita D",
    "parents_phone_number": "9000000020",
    "class_section": "10-C",
    "bus_no": "66",
    "is_bus_student": true,
    "address": "Auto Nagar",
    "transport_fee": 19000
  }
]
